# Generated by Django 3.0.7 on 2020-07-01 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='title',
            new_name='content',
        ),
    ]
